export type Product = {
  id: number;
  categoryId: number;
  name: string;
  barcode: string;
  price: number;
  discount: number;
  tax: number;
  threshold: number;
  stock: number;
  modifier?: string;
  imageUrl: string;
  isActive: boolean;
};

export const products: Product[] = [
  {
    id: 1,
    categoryId: 1,
    name: "Rice 5kg",
    barcode: "SRF-0001",
    price: 18500,
    discount: 0,
    tax: 0,
    threshold: 10,
    stock: 45,
    imageUrl: "/products/rice.jpeg",
    isActive: true,
  },
  {
    id: 2,
    categoryId: 1,
    name: "Cooking Oil 1L",
    barcode: "SRF-0002",
    price: 7200,
    discount: 0,
    tax: 0,
    threshold: 15,
    stock: 60,
    imageUrl: "/products/Cooking_oil.jpeg",
    isActive: true,
  },
  {
    id: 3,
    categoryId: 1,
    name: "Instant Noodles",
    barcode: "SRF-0003",
    price: 1200,
    discount: 0,
    tax: 0,
    threshold: 30,
    stock: 200,
    imageUrl: "/products/instant_noodle.jpeg",
    isActive: true,
  },
  {
    id: 4,
    categoryId: 1,
    name: "Canned Fish",
    barcode: "SRF-0004",
    price: 2800,
    discount: 0,
    tax: 0,
    threshold: 20,
    stock: 75,
    imageUrl: "/products/canned_fish.webp",
    isActive: true,
  },
  {
    id: 5,
    categoryId: 1,
    name: "Biscuits",
    barcode: "SRF-0005",
    price: 1800,
    discount: 0,
    tax: 0,
    threshold: 25,
    stock: 18,
    imageUrl: "/products/biscuits.jpeg",
    isActive: true,
  },
  {
    id: 6,
    categoryId: 2,
    name: "Water 500ml",
    barcode: "SRF-0006",
    price: 300,
    discount: 0,
    tax: 0,
    threshold: 50,
    stock: 300,
    imageUrl: "/products/water.jpeg",
    isActive: true,
  },
  {
    id: 7,
    categoryId: 2,
    name: "Green Tea",
    barcode: "SRF-0007",
    price: 1500,
    discount: 0,
    tax: 0,
    threshold: 20,
    stock: 80,
    imageUrl: "/products/green-tea.jpeg",
    isActive: true,
  },
  {
    id: 8,
    categoryId: 2,
    name: "Coffee Mix",
    barcode: "SRF-0008",
    price: 800,
    discount: 0,
    tax: 0,
    threshold: 20,
    stock: 120,
    imageUrl: "/products/coffee-mix.jpeg",
    isActive: true,
  },
  {
    id: 9,
    categoryId: 2,
    name: "Coca-Cola",
    barcode: "SRF-0009",
    price: 1000,
    discount: 0,
    tax: 0,
    threshold: 30,
    stock: 95,
    imageUrl: "/products/coca-cola.jpeg",
    isActive: true,
  },
  {
    id: 10,
    categoryId: 3,
    name: "Washing Powder",
    barcode: "SRF-0010",
    price: 4200,
    discount: 0,
    tax: 0,
    threshold: 15,
    stock: 8,
    imageUrl: "/products/washing-powder.jpeg",
    isActive: true,
  },
];
